### ISSUE TITLE
post请求崩溃 

### ISSUE THREAD

**Issue by Antduo** [caixindong/XDNetworking#1]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteData objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7ff769d6ded0'

**Comment by Antduo** [comment]
可以请求出数据,当我对请求回的数据进行遍历时,就出现了上述的崩溃

**Comment by caixindong** [comment]
可以贴出相关代码吗 @weibintao

**Comment by caixindong** [comment]
返回的数据默认是用JSON格式的 @weibintao

**Comment by Antduo** [comment]
这是请求回来的json字典
{
    TypeList =     (
                {
            typeName = "\U706b\U707e";
        },
                {
            typeName = "\U7535\U68af";
        },
                {
            typeName = "\U6cbb\U5b89";
        },
                {
            typeName = "\U4ea4\U901a\U4e8b\U6545";
        },
                {
            typeName = "\U8d22\U52a1\U635f\U6bc1";
        }
    );
    method = getEventReportTypes;
}

//代码如下:
NSMutableDictionary *dic = [NSMutableDictionary dictionary];
    dic[@"method"] = @"getEventReportTypes";
    dic[@"module"] = @"Common";

```
NSMutableDictionary *params = [NSMutableDictionary dictionary];
params[@"requestValue"] = [JsonTool getStringWithDic:dic];


[XDNetworking postWithUrl:@"http://120.25.78.157:9016/app/terminalapi/call" refreshRequest:YES cache:YES params:params progressBlock:nil successBlock:^(id response) {


    NSLog(@"=====================>>%@",response[@"TypeList"]);

} failBlock:^(NSError *error) {

}];
```

//我取字典中TypeList对应的数组,崩溃

**Comment by caixindong** [comment]
我这边测试没有问题，你再看看你那个response里的数据格式 @weibintao
