### ISSUE TITLE
你好，我用你的库里面的下载方法下载图片但是下载不了具体问题如下

### ISSUE THREAD

**Issue by DamonRao** [caixindong/XDNetworking#2]
打断点发现总是不走里面successBlock:^(NSURL *url) {  
            UIImage *img = [UIImage imageWithData:[NSData dataWithContentsOfURL:url]];
            [self.imageArray setObject:img atIndexedSubscript:index];
            
            LJLog(@"_imageArray2:-----%@",self.imageArray)；}里面的方法，你有下载图片的方法的demo给我参考一下吗

**Comment by caixindong** [comment]
请问你调用的是哪个api
